-- Authoritative GGMA 2026 schedule seed.
-- Source captured from https://goodwingoodge.com/fifty-runs/ on 2026-09-04.
-- The published source provides dates, states and cities but no start times, timezones or coordinates.

INSERT INTO ggma_race_schedule
  (id, operational_window_id, race_number, race_date, state, state_code, city, slug,
   scheduled_start_time, timezone, latitude, longitude, status, source_url, created_at, updated_at)
VALUES
  ('ggma-2026-01', 'ggma-2026',  1, '2026-10-09', 'Hawaii',         'HI', 'Honolulu',                    '01-hawaii-honolulu',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-02', 'ggma-2026',  2, '2026-10-10', 'Alaska',         'AK', 'Anchorage',                   '02-alaska-anchorage',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-03', 'ggma-2026',  3, '2026-10-10', 'Oregon',         'OR', 'Portland',                    '03-oregon-portland',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-04', 'ggma-2026',  4, '2026-10-11', 'Washington',     'WA', 'Vancouver',                   '04-washington-vancouver',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-05', 'ggma-2026',  5, '2026-10-11', 'Utah',           'UT', 'Salt Lake City',              '05-utah-salt-lake-city',                NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-06', 'ggma-2026',  6, '2026-10-12', 'Idaho',          'ID', 'Idaho Falls',                 '06-idaho-idaho-falls',                  NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-07', 'ggma-2026',  7, '2026-10-12', 'Montana',        'MT', 'Bozeman',                     '07-montana-bozeman',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-08', 'ggma-2026',  8, '2026-10-13', 'North Dakota',   'ND', 'Bowman',                      '08-north-dakota-bowman',                NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-09', 'ggma-2026',  9, '2026-10-13', 'South Dakota',   'SD', 'Keystone',                    '09-south-dakota-keystone',              NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-10', 'ggma-2026', 10, '2026-10-14', 'Wyoming',        'WY', 'Sundance',                    '10-wyoming-sundance',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-11', 'ggma-2026', 11, '2026-10-14', 'Nebraska',       'NE', 'Morrill',                     '11-nebraska-morrill',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-12', 'ggma-2026', 12, '2026-10-15', 'Colorado',       'CO', 'Denver',                      '12-colorado-denver',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-13', 'ggma-2026', 13, '2026-10-15', 'New Mexico',     'NM', 'Albuquerque',                 '13-new-mexico-albuquerque',             NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-14', 'ggma-2026', 14, '2026-10-16', 'Texas',          'TX', 'Dallas',                      '14-texas-dallas',                       NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-15', 'ggma-2026', 15, '2026-10-16', 'Oklahoma',       'OK', 'Afton',                       '15-oklahoma-afton',                     NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-16', 'ggma-2026', 16, '2026-10-17', 'Kansas',         'KS', 'Kansas City',                 '16-kansas-kansas-city',                 NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-17', 'ggma-2026', 17, '2026-10-17', 'Missouri',       'MO', 'Kansas City',                 '17-missouri-kansas-city',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-18', 'ggma-2026', 18, '2026-10-17', 'Minnesota',      'MN', 'Minneapolis',                 '18-minnesota-minneapolis',              NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-19', 'ggma-2026', 19, '2026-10-18', 'Iowa',           'IA', 'Lansing',                     '19-iowa-lansing',                       NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-20', 'ggma-2026', 20, '2026-10-18', 'Wisconsin',      'WI', 'De Soto',                     '20-wisconsin-de-soto',                  NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-21', 'ggma-2026', 21, '2026-10-19', 'Illinois',       'IL', 'Chicago',                     '21-illinois-chicago',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-22', 'ggma-2026', 22, '2026-10-19', 'Indiana',        'IN', 'South Bend',                  '22-indiana-south-bend',                 NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-23', 'ggma-2026', 23, '2026-10-19', 'Michigan',       'MI', 'Sturgis',                     '23-michigan-sturgis',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-24', 'ggma-2026', 24, '2026-10-20', 'Ohio',           'OH', 'Columbus',                    '24-ohio-columbus',                      NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-25', 'ggma-2026', 25, '2026-10-20', 'Arizona',        'AZ', 'Willow Beach / Hoover Dam',   '25-arizona-willow-beach-hoover-dam',   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-26', 'ggma-2026', 26, '2026-10-21', 'California',     'CA', 'Los Angeles',                 '26-california-los-angeles',             NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-27', 'ggma-2026', 27, '2026-10-21', 'Nevada',         'NV', 'Las Vegas',                   '27-nevada-las-vegas',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-28', 'ggma-2026', 28, '2026-10-22', 'Arkansas',       'AR', 'Little Rock',                 '28-arkansas-little-rock',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-29', 'ggma-2026', 29, '2026-10-22', 'Louisiana',      'LA', 'Shreveport',                  '29-louisiana-shreveport',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-30', 'ggma-2026', 30, '2026-10-23', 'Mississippi',    'MS', 'Meridian',                    '30-mississippi-meridian',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-31', 'ggma-2026', 31, '2026-10-23', 'Alabama',        'AL', 'Tuscaloosa',                  '31-alabama-tuscaloosa',                 NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-32', 'ggma-2026', 32, '2026-10-24', 'Florida',        'FL', 'Miami',                       '32-florida-miami',                      NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-33', 'ggma-2026', 33, '2026-10-24', 'Georgia',        'GA', 'Atlanta',                     '33-georgia-atlanta',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-34', 'ggma-2026', 34, '2026-10-25', 'South Carolina', 'SC', 'Greenville',                  '34-south-carolina-greenville',          NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-35', 'ggma-2026', 35, '2026-10-25', 'North Carolina', 'NC', 'Asheville',                   '35-north-carolina-asheville',           NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-36', 'ggma-2026', 36, '2026-10-25', 'Tennessee',      'TN', 'Pigeon Forge',                '36-tennessee-pigeon-forge',             NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-37', 'ggma-2026', 37, '2026-10-26', 'Virginia',       'VA', 'Norton',                      '37-virginia-norton',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-38', 'ggma-2026', 38, '2026-10-26', 'Kentucky',       'KY', 'Pikeville',                   '38-kentucky-pikeville',                 NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-39', 'ggma-2026', 39, '2026-10-27', 'West Virginia',  'WV', 'Hazelton',                    '39-west-virginia-hazelton',             NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-40', 'ggma-2026', 40, '2026-10-27', 'Maryland',       'MD', 'Elkton',                      '40-maryland-elkton',                    NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-41', 'ggma-2026', 41, '2026-10-28', 'Delaware',       'DE', 'Glasgow',                     '41-delaware-glasgow',                   NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-42', 'ggma-2026', 42, '2026-10-28', 'Pennsylvania',   'PA', 'Philadelphia',                '42-pennsylvania-philadelphia',          NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-43', 'ggma-2026', 43, '2026-10-29', 'New Jersey',     'NJ', 'Teterboro',                   '43-new-jersey-teterboro',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-44', 'ggma-2026', 44, '2026-10-29', 'Connecticut',    'CT', 'Stamford',                    '44-connecticut-stamford',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-45', 'ggma-2026', 45, '2026-10-30', 'Rhode Island',   'RI', 'Providence',                  '45-rhode-island-providence',            NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-46', 'ggma-2026', 46, '2026-10-30', 'Massachusetts',  'MA', 'Boston',                      '46-massachusetts-boston',               NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-47', 'ggma-2026', 47, '2026-10-30', 'Vermont',        'VT', 'Brattleboro',                 '47-vermont-brattleboro',                NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-48', 'ggma-2026', 48, '2026-10-31', 'New Hampshire',  'NH', 'Portsmouth',                  '48-new-hampshire-portsmouth',           NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-49', 'ggma-2026', 49, '2026-10-31', 'Maine',          'ME', 'Kittery',                     '49-maine-kittery',                      NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
  ('ggma-2026-50', 'ggma-2026', 50, '2026-11-01', 'New York',       'NY', 'New York City',               '50-new-york-new-york-city',             NULL, NULL, NULL, NULL, 'scheduled', 'https://goodwingoodge.com/fifty-runs/', UNIX_TIMESTAMP(), UNIX_TIMESTAMP())
ON DUPLICATE KEY UPDATE
  operational_window_id = VALUES(operational_window_id),
  race_date = VALUES(race_date),
  state = VALUES(state),
  state_code = VALUES(state_code),
  city = VALUES(city),
  slug = VALUES(slug),
  scheduled_start_time = VALUES(scheduled_start_time),
  timezone = VALUES(timezone),
  latitude = VALUES(latitude),
  longitude = VALUES(longitude),
  status = VALUES(status),
  source_url = VALUES(source_url),
  updated_at = UNIX_TIMESTAMP();
